---
title: "Report 5: Judges"
subtitle: "A casual report"
author: "Ricky Heinrich for Mélanie Méthot"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    toc: true
    extra_dependencies: ["float"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F, message = F, warning = F,fig.pos = "H")
```
```{r}
library(readr)
library(anytime)
library(stringr)
library(ggplot2)
library(lubridate)
library(dplyr)
library(knitr)
library(reshape2)
#library(kableExtra)
```

```{r}
states <- read_csv("../data/states.csv", show_col_types = FALSE)
```


```{r}
# judges <- kable(sort(table(states$JUDGE), decreasing = T))

judges <- data.frame(table(states$JUDGE))

judges
```

There are 1025 unique inputs for 'Judges'; way too many to go through manually. It looks like either the judges are separated by '/', or by ';'. So if we were to keep only the 'last' judge in a cell, we would keep everything after the last '/' or the last ';'. 

```{r eval = F}
# acknowledging my shortcomings: there is probably almost definitely a better way to do this
# created a new df to test out, next cell I edit in main df adding a singular new column
judges$Var2 <- sub(".*; ", "", judges$Var1) # after last ;
judges$Var3 <- sub(".*/ ", "", judges$Var2) # after last /
judges$Var4 <- sub(".*Judge ", "", judges$Var3) # after 'Judge'
judges$Var5 <- sub(".*Justice ", "", judges$Var4) # after 'Justice '
judges$Var6 <- sub(".*Justice\\n", "", judges$Var5) # after 'Justice/n'
judges$Var7 <- sub(", Chief Justice", "", judges$Var6) # remove ', Chief Justice'
judges$Var8 <- sub("His Honor ", "", judges$Var7) # remove 'His Honor '
judges$Var9 <- sub("Sir ", "", judges$Var8) # remove 'Sir ' 
judges$Var9 <- sub("Sir. ", "", judges$Var9) # remove 'Sir.'
judges$Var9 <- sub("\\(Sir", "", judges$Var9) # remove '(Sir'
judges$Var9 <- sub("DUFFY \\(Supreme Court\\), Marwick \\(Court of Petty Sessions\\)", "DUFFY", judges$Var9) # manually change the one where it seems supreme court should be chosen  
judges$Var9 <- sub("Billey \\(Lilley in 38\\)", "Lilley", judges$Var9) # replace Billey w/ Lilley b/c more Lilley
judges$Var10 <- sub("\\(.*\\)", "", judges$Var9) # remove parenthesis stuff
judges$Var10 <- tolower(judges$Var10) # convert all to lower case
judges$Var11 <- sub("[a-z]\\.[a-z]\\.", "", judges$Var10) # remove anything that is 'x.x.' 
judges$Var12 <- sub("mr\\. ", "", judges$Var11) # remove 'mr.'
judges$Var12 <- sub(" [a-z]\\.", "", judges$Var12) # remove ' x.'
judges$Var12 <- sub("^ +", "", judges$Var12) # remove space(s) at start of string
judges$Var12 <- sub(" +$", "", judges$Var12) # remove space(s) at end of string
judges$Var12 <- sub(",$", "", judges$Var12) # remove commas at end of string
judges$Var12 <- sub(" +$", "", judges$Var12) # remove space(s) at end of string (again)
judges$Var13 <- sub(".*martin.*", "martin", judges$Var12) # if has 'martin' then make 'martin'
judges$Var13 <- sub(".*duffy.*", "duffy", judges$Var13) # if has 'duffy' then make 'duffy'
judges$Var13 <- sub("mr\\. ", "", judges$Var13) # remove 'mr.' (again)
judges$Var13 <- sub(".*lowe.*", "lowe", judges$Var13) # if has 'lowe' then make 'lowe'
judges$Var13 <- sub("messrs\\. ", "", judges$Var13) # remove 'messrs.'
judges$Var13 <- sub("^[a-z]\\.", "", judges$Var13) # remove 'x.' from start
judges$Var13 <- sub("^ +", "", judges$Var13) # remove space(s) at start of string
judges$Var13 <- sub("\\.$", "", judges$Var13) # remove period at end
judges$Var13 <- sub(", [a-z]$", "", judges$Var13) # remove ', x' at end
judges$Var13 <- sub(" esq.*", "", judges$Var13) # remove everything after & include 'esq' (checked, 3 instances)
judges$Var13 <- sub(".*\\n", "", judges$Var13)
judges$Var13 <- sub(",[a-z]$", "", judges$Var13)
judges$Var13 <- sub("'s$", "", judges$Var13)
judges$Var13 <- sub(",[a-z]$", "", judges$Var13)
judges$Var13 <- sub(", [a-z]$", "", judges$Var13)
judges$Var13 <- sub(", +$", "", judges$Var13)
judges$Var13 <- sub(",[a-z]\\.[a-z]$", "", judges$Var13)
judges$Var14 <- sub(".*, ", "", judges$Var13) # everything after last comma
judges$Var15 <- sub(".* and ", "", judges$Var14) # everything after 'and'
judges$Var15 <- sub("^ +", "", judges$Var15) # remove space(s) at start of string
judges$Var15 <- sub(" +$", "", judges$Var15) # remove space(s) at end of string

# manually cleaning odd ones out
judges$Var15 <- sub("a jury of 12", "forbes", judges$Var15) # replacing this specific case that fell out in my 'and' assumption
judges$Var15 <- sub(" [a-z][a-z]$", "", judges$Var15) 
judges$Var15 <- sub(" [a-z][a-z]/$", "", judges$Var15) 
judges$Var15 <- sub("wilkinson took his place due to illness)", "wilkinson", judges$Var15) 
judges$Var15 <- sub("morrisonp", "morrison", judges$Var15) 
judges$Var15 <- sub("douglas see note", "douglas", judges$Var15) 
judges$Var15 <- sub("\"i cannot understand\" \" it was an improper thing to do\" \" it is a shameful state of affairs\"", "", judges$Var15) 
judges$Var15 <- sub("was not willing to take the case as a first offender", "", judges$Var15) 
judges$Var15 <- sub("her step father was examined but he was not asked a question about her misconduct.  andhe lied to wife # 2 ... wagner petition for reduced sentence", "faucett", judges$Var15) 
judges$Var15 <- sub("so lenient sentence!", "", judges$Var15) 

# final big step
judges$Var16 <- sub(".* ", "", judges$Var15) # keeping only stuff after last space
judges$Var16 <- sub(".*;", "", judges$Var16)
judges$Var16 <- sub("[\\)\\*+]", "", judges$Var16)
judges$Var16 <- sub("[\\)\\*+]", "", judges$Var16)
judges$Var16 <- sub("\\-+", "", judges$Var16)
judges <- judges %>%
    mutate(Var16 = ifelse(Var1 == "A.C.I.", "A.C.I.", Var16))

# test_str <- "name., k."
# sub("[,\\.]", "", test_str)

length(table(judges$Var1)) # 1025
length(table(judges$Var2)) # 783
length(table(judges$Var3)) # 778
length(table(judges$Var4)) # 720
length(table(judges$Var5)) # 676
length(table(judges$Var6)) # 673
length(table(judges$Var7)) # 671
length(table(judges$Var8)) # 669
length(table(judges$Var9)) # 669, 667, 666, 665
length(table(judges$Var10)) # 638, 607
length(table(judges$Var11)) # 606
length(table(judges$Var12)) # 603, 590, 584, 551, 540, 528
length(table(judges$Var13)) # 525, 522, 521, 518, 512, 509, 505, 501, 499
length(table(judges$Var14)) # 484
length(table(judges$Var15)) # 475, 474, 472, 471, 468, 467
length(table(judges$Var16)) # 424, 421


# judges[str_detect(judges$Var16, "[[:punct:][:digit:][:cntrl:]]"), "Var16"] not alpha
# judges[str_detect(judges$Var13, "[a-z]\\.$"), "Var13"]
# judges[str_detect(judges$Var10, "mr. buchanan"), "Var10"]
# judges[str_detect(judges$Var11, ",[a-z]\\."), "Var11"]


# filter(states[str_detect(states$JUDGE, "A.C.I."),], !is.na(states[str_detect(states$JUDGE, "A.C.I."),1]))
```

```{r}
# make all changes in original df in one new col ...

states$judge_simple <- sub(".*; ", "", states$JUDGE) # after last ;
states$judge_simple <- sub(".*/ ", "", states$judge_simple) # after last /
states$judge_simple <- sub(".*Judge ", "", states$judge_simple) # after 'Judge'
states$judge_simple <- sub(".*Justice ", "", states$judge_simple) # after 'Justice '
states$judge_simple <- sub(".*Justice\\n", "", states$judge_simple) # after 'Justice/n'
states$judge_simple <- sub(", Chief Justice", "", states$judge_simple) # remove ', Chief Justice'
states$judge_simple <- sub("His Honor ", "", states$judge_simple) # remove 'His Honor '
states$judge_simple <- sub("Sir ", "", states$judge_simple) # remove 'Sir ' 
states$judge_simple <- sub("Sir. ", "", states$judge_simple) # remove 'Sir.'
states$judge_simple <- sub("\\(Sir", "", states$judge_simple) # remove '(Sir'
states$judge_simple <- sub("DUFFY \\(Supreme Court\\), Marwick \\(Court of Petty Sessions\\)", "DUFFY", states$judge_simple) # manually change the one where it seems supreme court should be chosen  
states$judge_simple <- sub("Billey \\(Lilley in 38\\)", "Lilley", states$judge_simple) # replace Billey w/ Lilley b/c more Lilley
states$judge_simple <- sub("\\(.*\\)", "", states$judge_simple) # remove parenthesis stuff
states$judge_simple <- tolower(states$judge_simple) # convert all to lower case
states$judge_simple <- sub("[a-z]\\.[a-z]\\.", "", states$judge_simple) # remove anything that is 'x.x.' 
states$judge_simple <- sub("mr\\. ", "", states$judge_simple) # remove 'mr.'
states$judge_simple <- sub(" [a-z]\\.", "", states$judge_simple) # remove ' x.'
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string
states$judge_simple <- sub(",$", "", states$judge_simple) # remove commas at end of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string (again)
states$judge_simple <- sub(".*martin.*", "martin", states$judge_simple) # if has 'martin' then make 'martin'
states$judge_simple <- sub(".*duffy.*", "duffy", states$judge_simple) # if has 'duffy' then make 'duffy'
states$judge_simple <- sub("mr\\. ", "", states$judge_simple) # remove 'mr.' (again)
states$judge_simple <- sub(".*lowe.*", "lowe", states$judge_simple) # if has 'lowe' then make 'lowe'
states$judge_simple <- sub("messrs\\. ", "", states$judge_simple) # remove 'messrs.'
states$judge_simple <- sub("^[a-z]\\.", "", states$judge_simple) # remove 'x.' from start
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub("\\.$", "", states$judge_simple) # remove period at end
states$judge_simple <- sub(", [a-z]$", "", states$judge_simple) # remove ', x' at end
states$judge_simple <- sub(" esq.*", "", states$judge_simple) # remove everything after & include 'esq' (checked, 3 instances)
states$judge_simple <- sub("\\n$", "", states$judge_simple)
states$judge_simple <- sub(".*\\n", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]$", "", states$judge_simple)
states$judge_simple <- sub("'s$", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]$", "", states$judge_simple)
states$judge_simple <- sub(", [a-z]$", "", states$judge_simple)
states$judge_simple <- sub(", +$", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]\\.[a-z]$", "", states$judge_simple)
states$judge_simple <- sub(".*, ", "", states$judge_simple) # everything after last comma
states$judge_simple <- sub(".* and ", "", states$judge_simple) # everything after 'and'
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string

# manually cleaning odd ones out
states$judge_simple <- sub("a jury of 12", "forbes", states$judge_simple) # replacing this specific case that fell out in my 'and' assumption
states$judge_simple <- sub(" [a-z][a-z]$", "", states$judge_simple) 
states$judge_simple <- sub(" [a-z][a-z]/$", "", states$judge_simple) 
states$judge_simple <- sub("wilkinson took his place due to illness)", "wilkinson", states$judge_simple) 
states$judge_simple <- sub("morrisonp", "morrison", states$judge_simple) 
states$judge_simple <- sub("douglas see note", "douglas", states$judge_simple) 
states$judge_simple <- sub("\"i cannot understand\" \" it was an improper thing to do\" \" it is a shameful state of affairs\"", "", states$judge_simple) 
states$judge_simple <- sub("was not willing to take the case as a first offender", "", states$judge_simple) 
states$judge_simple <- sub("her step father was examined but he was not asked a question about her misconduct.  andhe lied to wife # 2 ... wagner petition for reduced sentence", "faucett", states$judge_simple) 
states$judge_simple <- sub("so lenient sentence!", "", states$judge_simple) 

# final big step
states$judge_simple <- sub(".* ", "", states$judge_simple) # keeping only stuff after last space
states$judge_simple <- sub(".*;", "", states$judge_simple)
states$judge_simple <- sub("[\\)\\*+]", "", states$judge_simple)
states$judge_simple <- sub("[\\)\\*+]", "", states$judge_simple)
states$judge_simple <- sub("\\-+", "", states$judge_simple)
states <- states %>%
    mutate(judge_simple = ifelse(JUDGE== "A.C.I.", "A.C.I.", judge_simple))
```

```{r}
kable(sort(table(states$judge_simple), decreasing = T)[1:10])
```

```{r}
sentences <- subset(states, select= c(SENTENCE, judge_simple))
sentences$var2 <- sub("motnhs", "months", sentences$SENTENCE) # fix obvious typo
sentences$var2 <- tolower(sentences$var2) # make all lower case
sentences$var2 <- sub("montsh", "months", sentences$var2) # fix other typo
sentences$var2 <- sub(", hl$", "", sentences$var2)
sentences$var2 <- sub("15 months, hl - in total\\n\\n9 months, hl - bigamy\\n6 months, hl - perjury", "9 months", sentences$var2) # subjective fixing
sentences$var2 <- sub("6 years, hl \\n\\n\\(3 years - bigamy, 3 years - making a false statement, served concurrently\\)", "3 years", sentences$var2)
sentences$var2 <- sub("monhs", "months", sentences$var2)
sentences$var3 <- sub(".*suspended.*", "suspended", sentences$var2) # suspended
sentences$var3 <- sub(".*sispended.*", "suspended", sentences$var3)
sentences$var3 <- sub(".*3 years to be served in total.*", "2 years", sentences$var3)
sentences$var3 <- sub(".*stated that she was a spinster to the officiating clergyman.*", "6 months", sentences$var3)
sentences$var3 <- sub(" \\(.*\\)", "", sentences$var3)
sentences$var3 <- sub(" but.*", "", sentences$var3)
sentences$var4 <- gsub("[.]", "", sentences$var3) # just found out the difference b/w sub and gsub :)
sentences$var4 <- gsub(" *hl", "", sentences$var4)
sentences$var5 <- gsub(".*own recognizance.*", "own recognizance", sentences$var4)
sentences$var5 <- gsub(" *; *", "", sentences$var5)
sentences$var5 <- sub(".*the case documents and the article.*", "discharged", sentences$var5)
sentences$var5 <- sub(",.*", "", sentences$var5) # remove everything after comma
sentences$var5 <- sub(" cumulative!", "", sentences$var5) 
sentences$var5 <- sub(".*7 years.*", "7 years", sentences$var5) 
sentences$var6 <- sub(" *ll", "", sentences$var5) 
sentences$var6 <- sub("month$", "months", sentences$var6) # includes 1 month -> 1 months
sentences$var6 <- sub("^12 months.*", "12 months", sentences$var6) # if starts with 12 months
sentences$var6 <- sub("^18 months.*", "18 months", sentences$var6)
sentences$var6 <- sub("^2 years.*", "2 years", sentences$var6)
sentences$var6 <- sub("^2 yrs*", "2 years", sentences$var6)
sentences$var6 <- sub("^2 1/2 years*", "2 years", sentences$var6)
sentences$var6 <- sub("^3 months.*", "3 months", sentences$var6)
sentences$var6 <- sub("^3 years.*", "3 years", sentences$var6)
sentences$var6 <- sub("^4 years.*", "4 years", sentences$var6)
sentences$var6 <- sub("^5 years.*", "5 years", sentences$var6)
sentences$var6 <- sub("^6 months.*", "6 months", sentences$var6)
sentences$var6 <- sub("^ac.*", "acquitted", sentences$var6)
sentences$var6 <- sub("^case dismissed.*", "dismissed", sentences$var6)
sentences$var6 <- sub("^aquitted.*", "acquitted", sentences$var6)
sentences$var6 <- sub("two sentences of two years to be served one after the other", "4 years", sentences$var6)
sentences$var6 <- sub("^escap.*", "escaped", sentences$var6)
# unknown, DNS, rising of court, 6 months and less, 9 months, 12 months, 18 months, 2 years, >3 years
sentences$var7 <- sub("\\?", "unknown", sentences$var6)
sentences$var7 <- sub(".*guilty", "unknown", sentences$var7)

sentences$var7 <- sub("half an hour", "rising of the court", sentences$var7)
sentences$var7 <- sub("^1 day", "rising of the court", sentences$var7)
sentences$var7 <- sub("^(?:[1-9]|1[0-9]|2[0-4]) hour.*", "rising of the court", sentences$var7)
sentences$var7 <- sub("10 minutes", "rising of the court", sentences$var7)

sentences$var7 <- sub("^[1-6] *months *", "6 months and less", sentences$var7)
sentences$var7 <- sub("^[0-9]* week.*", "6 months and less", sentences$var7)
sentences$var7 <- sub("^[0-9]* day.*", "6 months and less", sentences$var7)

sentences$var7 <- sub("^8 months", "9 months", sentences$var7)
sentences$var7 <- sub("10 months", "9 months", sentences$var7)

sentences$var7 <- sub("1[1-5] months", "12 months", sentences$var7)
sentences$var7 <- sub("1[6-9] months", "18 months", sentences$var7)
sentences$var7 <- sub("2[0-9] months", "2 years", sentences$var7)
sentences$var7 <- sub("3[0-3] months", "2 years", sentences$var7)
sentences$var7 <- sub("[3-9] y.*", "3 years and more", sentences$var7)

sentences$var7 <- sub("dead", "other", sentences$var7)
sentences$var7 <- sub("escaped", "other", sentences$var7)
sentences$var7 <- sub("found drowned", "other", sentences$var7)
sentences$var7 <- sub("insane", "other", sentences$var7)
sentences$var7 <- sub("murdered by her husband while on bail", "other", sentences$var7)
sentences$var7 <- sub("no appearance", "other", sentences$var7)
sentences$var7 <- sub("suicide", "other", sentences$var7)
sentences$var7 <- sub("warrent", "other", sentences$var7)
sentences$var7 <- sub("absconded", "other", sentences$var7)

# anything that is not unknown, other, rising of the court, or starts with a digit is DNS

test_str <- c("90 hours", "unknown", "random","ass", "shit")

ifelse(!(test_str %in% c("unknown", "other", "rising of the court")) & !str_detect(test_str, "^[1-9].*"), paste("yes"), paste("no"))

sentences$var8 <- ifelse(!(sentences$var7 %in% c("unknown", "other", "rising of the court")) & !str_detect(sentences$var7, "^[1-9].*"), sub(".*", "D.N.S.", sentences$var7), sentences$var7)

sentences$var9 <- sub("3.*", ">3", sentences$var8)
sentences$var9 <- sub("6.*", "<6", sentences$var9)
sentences$var9 <- sub("rising.*", "ris", sentences$var9)

length(table(sentences$SENTENCE)) # 326
length(table(sentences$var2)) # 319, 277, 275, 261, 259, 258
length(table(sentences$var3)) # 236, 229, 227
length(table(sentences$var4)) # 200, 175
length(table(sentences$var5)) # 156, 135, 134, 127, 126, 123
length(table(sentences$var6)) # 115, 112, 107, 104, 98, 97,96, 93, 87, 84, 80, 76, 73
length(table(sentences$var7)) 

sentences[!str_detect(sentences$var3, " hl") & str_detect(sentences$var3, "hl"), "var3"]

sentences[str_detect(sentences$var5, "[:punct:]") & !str_detect(sentences$var5, "\\?"), "var5"]
unique(sentences[str_detect(sentences$var6, ".*guilty"), "var6"])
states[str_detect(states$SENTENCE, "to be served"), ]
```

```{r}
kable(table(sentences$var8))

```

```{r}
# see if trend in sentence with top 10 judges?
# add states to see if trend in states?
sentences %>% group_by(judge_simple) %>% filter(n() >= 20)

table(sentences[sentences$judge_simple %in% names(head(sort(table(sentences$judge_simple), decreasing = T), 10)), "judge_simple"], sentences[sentences$judge_simple %in% names(head(sort(table(sentences$judge_simple), decreasing = T), 10)), "var9"])

df_top10judges <- sentences[sentences$judge_simple %in% names(head(sort(table(sentences$judge_simple), decreasing = T), 10)), ]



# I want, in this new df, the count total for each judge. then the count for each sentence. then the percentage for each sentence. I also want to sort the sentences in order of severity.

custom_order <- c("unknown", "D.N.S.", "ris", "<6", "9 months", "12 months", "18 months", "2 years", ">3" )

df_top10judges$var9 <- factor(df_top10judges$var9, levels = custom_order)

df_freq <- data.frame(table(df_top10judges$judge_simple, df_top10judges$var9))

df_freq <- dcast(df_freq, Var1~Var2, value.var = "Freq")

df_freq$sum <- rowSums(df_freq[,-1])

df_freq <- df_freq %>% mutate(across(2:10, ~round(./sum,2), .names = "{col}_prop"))

summary(df_freq)
```

