---
title: "wrangling & cleaning"
author: "Ricky Heinrich"
date: "`r Sys.Date()`"
output: html_document
---
# update df aug17
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  message = F, warning = F)
```

```{r}
library(readr)
library(anytime)
library(stringr)
library(ggplot2)
library(lubridate)
library(dplyr)
```

```{r}
# importing all data
allNSW <- read_csv("../data/states_csv/NSW - Sheet1.csv", show_col_types = FALSE)
allQueensland <- read_csv("../data/states_csv/Queensland - Sheet1.csv", show_col_types = FALSE)
allSouth_Australia <- read_csv("../data/states_csv/South Australia - Sheet1.csv", show_col_types = FALSE)
allTasmania <- read_csv("../data/states_csv/Tasmania - Sheet1.csv", show_col_types = FALSE)
allVictoria <- read_csv("../data/states_csv/Victoria - Victoria.csv",show_col_types = FALSE)
allWestern_Australia <- read_csv("../data/states_csv/Western Australia - Sheet1.csv",show_col_types = FALSE)
```

```{r}
# WRANGLING & CLEANING DATES
# only keeping rows I'm interested in: date, gender, plea, judge, sentence, # articles, marriage dates, link1
# (this is dependent on no new columns being added and changing the index of cols)
NSW <- subset(allNSW, select = c(DATE, NAME, GENDER,PLEA,JUDGE,SENTENCE,14,25,30,36,Link1,20))
Queensland <- subset(allQueensland, select = c(DATE, NAME,GENDER,PLEA,JUDGE,SENTENCE,14,25,30,35,Link1,20))
South_Australia <- subset(allSouth_Australia, select = c(1,NAME, GENDER,PLEA,JUDGE,SENTENCE,14,25,30,35,Link1,20))
Tasmania <- subset(allTasmania, select = c(1, NAME,GENDER,Plea,JUDGE,SENTENCE,14,25,30,35,Link1,20))
Western_Australia <- subset(allWestern_Australia, select = c(1,NAME, GENDER,PLEA,JUDGE,SENTENCE,14,25,30,35,Link1,20))
Victoria <- subset(allVictoria, select = c(1, NAME, 20,PLEA,JUDGE,SENTENCE,15,26,31,36,Link1,21))

# standardizing column names
#states <- list(NSW, Queensland,South_Australia,Tasmania,Victoria,Western_Australia)
names_col <- c("DATE", "NAME","GENDER","PLEA","JUDGE","SENTENCE","num_articles", "FIRST_", "SECOND_", "THIRD_", "link1", "age")
colnames(South_Australia) <- names_col
colnames(Tasmania) <-names_col
colnames(Western_Australia) <- names_col
colnames(Victoria) <- names_col
colnames(Queensland) <- names_col
colnames(NSW) <- names_col

# adding column with state name; probably an easier way to do this
NSW <- cbind('NSW', NSW); colnames(NSW)[1] <- 'state'
Queensland <- cbind('Queensland', Queensland); colnames(Queensland)[1] <- 'state'
South_Australia <- cbind('South_Australia', South_Australia); colnames(South_Australia)[1] <- 'state'
Tasmania <- cbind('Tasmania', Tasmania); colnames(Tasmania)[1] <- 'state'
Western_Australia <- cbind('Western_Australia', Western_Australia); colnames(Western_Australia)[1] <- 'state'
Victoria <- cbind('Victoria', Victoria); colnames(Victoria)[1] <- 'state'

# convert date to character
South_Australia$DATE <- as.character(South_Australia$DATE)
Western_Australia$DATE <- as.character(Western_Australia$DATE)

# merging all together
states <- rbind(NSW, Queensland,South_Australia,Tasmania,Western_Australia,Victoria)

# removing rows with no dates
states <- states[!(is.na(states$DATE)), ]
# resetting index
rownames(states) <- NULL 

# clean typos
states$DATE <- str_replace_all(states$DATE,"--","-")
# states[1681,2] <- "1949-07-27" # fixed in og sheet and redownloaded; realized that when update the source files then the row index may change and this line will mess things up

#states$Date <- as.Date(states$DATE, format = "%Y-%m-%d") # this doesn't work b/c apparently as.Date only starts from 1970 ...

# Convert character date to date format using the 'anydate()' function
states$Date <- anydate(states$DATE)
```

```{r}
# CLEANING GENDER
# table(states$GENDER, exclude = NULL) # inspect
states$GENDER <- tolower(states$GENDER) # convert all to lower case
states$GENDER <- str_replace_all(states$GENDER, "males", "male")
# states[is.na(states$GENDER),] # checking which have gender missing, changing in og sheet and redownloading

```

```{r}
# CLEANING MARRIAGE DATES
# I want to extract the year from text: so any time have four digits in a row
#states[1317,9] <- "May 28 1938" #changed in og
# extract the first 'year' from string
states <- states %>%
  mutate(first_marriage = str_extract(FIRST_, "\\d{4}"))
states <- states %>%
  mutate(second_marriage = str_extract(SECOND_, "\\d{4}"))
states <- states %>%
  mutate(third_marriage = str_extract(THIRD_, "\\d{4}"))

# check if string contains multiple years, add to indicator column
states <- states %>%
  mutate(ind_first_marriage = str_count(FIRST_, "\\d{4}"))
states <- states %>%
  mutate(ind_second_marriage = str_count(SECOND_, "\\d{4}"))
states <- states %>%
  mutate(ind_third_marriage = str_count(THIRD_, "\\d{4}"))

# remove all \n in text (at least in that one column it was bothering me)
states$SECOND_ <- str_replace_all(states$SECOND_, "[\\n]+", "")

#table(states$ind_first_marriage) # if 0, then have string but no date, if NA then no string

#filter(states, ind_first_marriage == 0)[c(8,14,16)]
#filter(states, ind_first_marriage == 2,)[c(8,14,16)]
#filter(states, ind_first_marriage == 3)[c(8,14,16)]


```

```{r}

```
# I need to add tests to ensure everything is ok....
what can I check?
- 2 genders
- 

```{r}
# EXPORTING AS CSV
write_csv(states, "../data/states.csv")
```



# clean ... 
```{r}
# cleaning judges
# acknowledging my shortcomings: there is probably almost definitely a better way to do this

states$judge_simple <- sub(".*; ", "", states$JUDGE) # after last ;
states$judge_simple <- sub(".*/ ", "", states$judge_simple) # after last /
states$judge_simple <- sub(".*Judge ", "", states$judge_simple) # after 'Judge'
states$judge_simple <- sub(".*Justice ", "", states$judge_simple) # after 'Justice '
states$judge_simple <- sub(".*Justice\\n", "", states$judge_simple) # after 'Justice/n'
states$judge_simple <- sub(", Chief Justice", "", states$judge_simple) # remove ', Chief Justice'
states$judge_simple <- sub("His Honor ", "", states$judge_simple) # remove 'His Honor '
states$judge_simple <- sub("Sir ", "", states$judge_simple) # remove 'Sir ' 
states$judge_simple <- sub("Sir. ", "", states$judge_simple) # remove 'Sir.'
states$judge_simple <- sub("\\(Sir", "", states$judge_simple) # remove '(Sir'
states$judge_simple <- sub("DUFFY \\(Supreme Court\\), Marwick \\(Court of Petty Sessions\\)", "DUFFY", states$judge_simple) # manually change the one where it seems supreme court should be chosen  
states$judge_simple <- sub("Billey \\(Lilley in 38\\)", "Lilley", states$judge_simple) # replace Billey w/ Lilley b/c more Lilley
states$judge_simple <- sub("\\(.*\\)", "", states$judge_simple) # remove parenthesis stuff
states$judge_simple <- tolower(states$judge_simple) # convert all to lower case
states$judge_simple <- sub("[a-z]\\.[a-z]\\.", "", states$judge_simple) # remove anything that is 'x.x.' 
states$judge_simple <- sub("mr\\. ", "", states$judge_simple) # remove 'mr.'
states$judge_simple <- sub(" [a-z]\\.", "", states$judge_simple) # remove ' x.'
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string
states$judge_simple <- sub(",$", "", states$judge_simple) # remove commas at end of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string (again)
states$judge_simple <- sub(".*martin.*", "martin", states$judge_simple) # if has 'martin' then make 'martin'
states$judge_simple <- sub(".*duffy.*", "duffy", states$judge_simple) # if has 'duffy' then make 'duffy'
states$judge_simple <- sub("mr\\. ", "", states$judge_simple) # remove 'mr.' (again)
states$judge_simple <- sub(".*lowe.*", "lowe", states$judge_simple) # if has 'lowe' then make 'lowe'
states$judge_simple <- sub("messrs\\. ", "", states$judge_simple) # remove 'messrs.'
states$judge_simple <- sub("^[a-z]\\.", "", states$judge_simple) # remove 'x.' from start
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub("\\.$", "", states$judge_simple) # remove period at end
states$judge_simple <- sub(", [a-z]$", "", states$judge_simple) # remove ', x' at end
states$judge_simple <- sub(" esq.*", "", states$judge_simple) # remove everything after & include 'esq' (checked, 3 instances)
states$judge_simple <- sub("\\n$", "", states$judge_simple)
states$judge_simple <- sub(".*\\n", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]$", "", states$judge_simple)
states$judge_simple <- sub("'s$", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]$", "", states$judge_simple)
states$judge_simple <- sub(", [a-z]$", "", states$judge_simple)
states$judge_simple <- sub(", +$", "", states$judge_simple)
states$judge_simple <- sub(",[a-z]\\.[a-z]$", "", states$judge_simple)
states$judge_simple <- sub(".*, ", "", states$judge_simple) # everything after last comma
states$judge_simple <- sub(".* and ", "", states$judge_simple) # everything after 'and'
states$judge_simple <- sub("^ +", "", states$judge_simple) # remove space(s) at start of string
states$judge_simple <- sub(" +$", "", states$judge_simple) # remove space(s) at end of string

# manually cleaning odd ones out
states$judge_simple <- sub("a jury of 12", "forbes", states$judge_simple) # replacing this specific case that fell out in my 'and' assumption
states$judge_simple <- sub(" [a-z][a-z]$", "", states$judge_simple) 
states$judge_simple <- sub(" [a-z][a-z]/$", "", states$judge_simple) 
states$judge_simple <- sub("wilkinson took his place due to illness)", "wilkinson", states$judge_simple) 
states$judge_simple <- sub("morrisonp", "morrison", states$judge_simple) 
states$judge_simple <- sub("douglas see note", "douglas", states$judge_simple) 
states$judge_simple <- sub("\"i cannot understand\" \" it was an improper thing to do\" \" it is a shameful state of affairs\"", "", states$judge_simple) 
states$judge_simple <- sub("was not willing to take the case as a first offender", "", states$judge_simple) 
states$judge_simple <- sub("her step father was examined but he was not asked a question about her misconduct.  andhe lied to wife # 2 ... wagner petition for reduced sentence", "faucett", states$judge_simple) 
states$judge_simple <- sub("so lenient sentence!", "", states$judge_simple) 

# final big step
states$judge_simple <- sub(".* ", "", states$judge_simple) # keeping only stuff after last space
states$judge_simple <- sub(".*;", "", states$judge_simple)
states$judge_simple <- sub("[\\)\\*+]", "", states$judge_simple)
states$judge_simple <- sub("[\\)\\*+]", "", states$judge_simple)
states$judge_simple <- sub("\\-+", "", states$judge_simple)
states <- states %>%
    mutate(judge_simple = ifelse(JUDGE== "A.C.I.", "A.C.I.", judge_simple))

states[states==""] <- NA

# checking typos
states$judge_simple <- sub("^archdal$", "archdall", states$judge_simple) # archdal -> archdall
states$judge_simple <- sub("^armstong$", "armstrong", states$judge_simple) # armstong -> armstrong
states$judge_simple <- sub("^bakchouse$", "backhouse", states$judge_simple) # 	bakchouse -> backhouse
states$judge_simple <- sub("^bracewelll$", "bracewell", states$judge_simple) # bracewelll -> bracewell
states$judge_simple <- sub("^m\\'farland$", "mcfarland", states$judge_simple) # m'farland -> mcfarland
states$judge_simple <- sub("^markel$", "markell", states$judge_simple) # markel -> markell
states$judge_simple <- sub("^o *[’']* *brya.$", "o'bryan", states$judge_simple) # o’bryab, obryan, o '  -> o’bryan
states$judge_simple <- sub("^sm$", "king", states$judge_simple) # checked case
```

```{r}
# cleaning sentences
states$sentence_simple <- sub("motnhs", "months", states$SENTENCE) # fix obvious typo
states$sentence_simple <- tolower(states$sentence_simple) # make all lower case
states$sentence_simple <- sub("montsh", "months", states$sentence_simple) # fix other typo
states$sentence_simple <- sub(", hl$", "", states$sentence_simple)
states$sentence_simple <- sub("15 months, hl - in total\\n\\n9 months, hl - bigamy\\n6 months, hl - perjury", "9 months", states$sentence_simple) # subjective fixing
states$sentence_simple <- sub("6 years, hl \\n\\n\\(3 years - bigamy, 3 years - making a false statement, served concurrently\\)", "3 years", states$sentence_simple)
states$sentence_simple <- sub("monhs", "months", states$sentence_simple)
states$sentence_simple <- sub(".*suspended.*", "suspended", states$sentence_simple) # suspended
states$sentence_simple <- sub(".*sispended.*", "suspended", states$sentence_simple)
states$sentence_simple <- sub(".*3 years to be served in total.*", "2 years", states$sentence_simple)
states$sentence_simple <- sub(".*stated that she was a spinster to the officiating clergyman.*", "6 months", states$sentence_simple)
states$sentence_simple <- sub(" \\(.*\\)", "", states$sentence_simple)
states$sentence_simple <- sub(" but.*", "", states$sentence_simple)
states$sentence_simple <- gsub("[.]", "", states$sentence_simple) # just found out the difference b/w sub and gsub :)
states$sentence_simple <- gsub(" *hl", "", states$sentence_simple)
states$sentence_simple <- gsub(".*own recognizance.*", "own recognizance", states$sentence_simple)
states$sentence_simple <- gsub(" *; *", "", states$sentence_simple)
states$sentence_simple <- sub(".*the case documents and the article.*", "discharged", states$sentence_simple)
states$sentence_simple <- sub(",.*", "", states$sentence_simple) # remove everything after comma
states$sentence_simple <- sub(" cumulative!", "", states$sentence_simple) 
states$sentence_simple <- sub(".*7 years.*", "7 years", states$sentence_simple) 
states$sentence_simple <- sub(" *ll", "", states$sentence_simple) 
states$sentence_simple <- sub("month$", "months", states$sentence_simple) # includes 1 month -> 1 months
states$sentence_simple <- sub("^12 months.*", "12 months", states$sentence_simple) # if starts with 12 months
states$sentence_simple <- sub("^18 months.*", "18 months", states$sentence_simple)
states$sentence_simple <- sub("^2 years.*", "2 years", states$sentence_simple)
states$sentence_simple <- sub("^2 yrs*", "2 years", states$sentence_simple)
states$sentence_simple <- sub("^2 1/2 years*", "2 years", states$sentence_simple)
states$sentence_simple <- sub("^3 months.*", "3 months", states$sentence_simple)
states$sentence_simple <- sub("^3 years.*", "3 years", states$sentence_simple)
states$sentence_simple <- sub("^4 years.*", "4 years", states$sentence_simple)
states$sentence_simple <- sub("^5 years.*", "5 years", states$sentence_simple)
states$sentence_simple <- sub("^6 months.*", "6 months", states$sentence_simple)
states$sentence_simple <- sub("^ac.*", "acquitted", states$sentence_simple)
states$sentence_simple <- sub("^case dismissed.*", "dismissed", states$sentence_simple)
states$sentence_simple <- sub("^aquitted.*", "acquitted", states$sentence_simple)
states$sentence_simple <- sub("two sentences of two years to be served one after the other", "4 years", states$sentence_simple)
states$sentence_simple <- sub("^escap.*", "escaped", states$sentence_simple)
# unknown, DNS, rising of court, 6 months and less, 9 months, 12 months, 18 months, 2 years, >3 years
states$sentence_simple <- sub("\\?", "unknown", states$sentence_simple)
states$sentence_simple <- sub(".*guilty", "unknown", states$sentence_simple)

states$sentence_simple <- sub("half an hour", "rising of the court", states$sentence_simple)
states$sentence_simple <- sub("^1 day", "rising of the court", states$sentence_simple)
states$sentence_simple <- sub("^(?:[1-9]|1[0-9]|2[0-4]) hour.*", "rising of the court", states$sentence_simple)
states$sentence_simple <- sub("10 minutes", "rising of the court", states$sentence_simple)

states$sentence_simple <- sub("^[1-6] *months *", "6 months and less", states$sentence_simple)
states$sentence_simple <- sub("^[0-9]* week.*", "6 months and less", states$sentence_simple)
states$sentence_simple <- sub("^[0-9]* day.*", "6 months and less", states$sentence_simple)

states$sentence_simple <- sub("^8 months", "9 months", states$sentence_simple)
states$sentence_simple <- sub("10 months", "9 months", states$sentence_simple)

states$sentence_simple <- sub("1[1-5] months", "12 months", states$sentence_simple)
states$sentence_simple <- sub("1[6-9] months", "18 months", states$sentence_simple)
states$sentence_simple <- sub("2[0-9] months", "2 years", states$sentence_simple)
states$sentence_simple <- sub("3[0-3] months", "2 years", states$sentence_simple)
states$sentence_simple <- sub("[3-9] y.*", "3 years and more", states$sentence_simple)

states$sentence_simple <- sub("dead", "other", states$sentence_simple)
states$sentence_simple <- sub("escaped", "other", states$sentence_simple)
states$sentence_simple <- sub("found drowned", "other", states$sentence_simple)
states$sentence_simple <- sub("insane", "other", states$sentence_simple)
states$sentence_simple <- sub("murdered by her husband while on bail", "other", states$sentence_simple)
states$sentence_simple <- sub("no appearance", "other", states$sentence_simple)
states$sentence_simple <- sub("suicide", "other", states$sentence_simple)
states$sentence_simple <- sub("warrent", "other", states$sentence_simple)
states$sentence_simple <- sub("absconded", "other", states$sentence_simple)
states$sentence_simple <- sub(".*sent to.*", "other", states$sentence_simple)

states$sentence_simple <- ifelse(!(states$sentence_simple %in% c("unknown", "other", "rising of the court")) & !str_detect(states$sentence_simple, "^[1-9].*"), sub(".*", "D.N.S.", states$sentence_simple), states$sentence_simple)

states$sentence_simple <- sub("3.*", "3_more", states$sentence_simple)
states$sentence_simple <- sub("6.*", "less_6", states$sentence_simple)
states$sentence_simple <- sub("rising.*", "ris", states$sentence_simple)

states$sentence_simple <- states$sentence_simple %>% replace_na('unknown')

# factoring the sentences
order_sentences <- c("unknown", "other","D.N.S.", "ris", "less_6", "9 months", "12 months", "18 months", "2 years", "3_more" )
states$sentence_simple <- factor(states$sentence_simple, levels = order_sentences)

```

```{r}
write_csv(states, "../data/states_clean.csv")
```

